### ISSUE TITLE
socket sever not available

### ISSUE THREAD

**Issue by caboo2** [Wizard2069/ant-media-livestream-demo#1]
Hi, nice project but it seems to lack to socket server for the messages thank you....

**Comment by Wizard2069** [comment]
Thanks for your concern, you can clone socket server here: https://github.com/Wizard2069/ant-media-demo.git. Anyway this project is just for demo so my design can be a bit clumsy.

**Comment by caboo2** [comment]
i think it has a listening port of localhost:8080; if its an api or socket service , i cant find it here  [https://github.com/Wizard2069/ant-media-demo.git](https://github.com/Wizard2069/ant-media-demo.git) thank you.

**Comment by Wizard2069** [comment]
> i think it has a listening port of localhost:8080; if its an api or socket service , i cant find it here https://github.com/Wizard2069/ant-media-demo.git and i think its for the chat feature. thank you.

You can run project inside ant-media-messaging-demo which is a Spring project, it opens a socket server and listen for message from client.
